name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa
      shell: /usr/bin/bash -e {0}

    - name: Verify SSH connection
      run: ssh -o StrictHostKeyChecking=no root@bot.fastmicroservices.com 'echo "SSH connection successful"'
      shell: /usr/bin/bash -e {0}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc g++ git

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Kill existing instance on the server
      run: ssh -o StrictHostKeyChecking=no root@bot.fastmicroservices.com '/root/kill' || true
      shell: /usr/bin/bash -e {0}

    - name: Copy binary to the server
      run: scp -o StrictHostKeyChecking=no build/MyBotApp root@bot.fastmicroservices.com:/root/bot
      shell: /usr/bin/bash -e {0}

    - name: Run new instance
      run: ssh -o StrictHostKeyChecking=no root@bot.fastmicroservices.com '/root/start'
      shell: /usr/bin/bash -e {0}