name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc g++ git

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Kill existing instance on the server
        ssh -o StrictHostKeyChecking=no root@bot.fastmicroservices.com 'pkill -f bot'

        # Copy binary to the server
        scp -o StrictHostKeyChecking=no build/MyBotApp root@bot.fastmicroservices.com:/root/bot

        # Run new instance
        ssh -o StrictHostKeyChecking=no root@bot.fastmicroservices.com 'nohup /root/bot > /dev/null 2>&1 &'
