name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc g++ git

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Copy binary to the server
        scp -o StrictHostKeyChecking=no build/MyBotApp user@yourserver:/root/bot

        # Kill existing instance and run new one
        ssh -o StrictHostKeyChecking=no user@yourserver << 'EOF'
          pkill -f bot
          nohup /root/bot > /dev/null 2>&1 &
        EOF
